### Register user
POST http://localhost:8090/register
Content-Type: application/json

{
    "firstName": "Björn",
    "lastName": "Schmitt",
    "emailaddress":"fantasy@gmail.com",
    "password": "dgsegrg"
}


### Create a movie
POST http://localhost:8090/
Authorization: Bearer aaa.bbb.ccc
Content-Type: application/json

{
    "movieName": "E.T.",
    "length": 104,
    "genre":"fantasy",
    "shows": {
        "room": "apollo",
        "date": "01.06.22",
        "time":"18:00"
    }
}